MESSAGE_BREAK = "\\n"
JOB_REQUEST = "JOBREQUEST"
JOB_STATUS = "JOBSTATUS"
JOB_RESULTS = "JOBRESULTS"
JOB_CANCEL = "JOBCANCEL"
HEALTH_REQUEST = "HEALTHREQUEST"
CLEAR_LOGS = "CLEARLOGS"
KILL = "KILL"
RESTART = "RESTART"
STOP_JOBS = "STOPJOBS"


TEMP_DIR = ".temp"
LOGS_DIR = ".logs"
JOB_RESULTS_DIR = ".jobResults"
WEB_LOGS_DIR = ".web_logs"

WEB_LOG_FILENAME = "web_log"
AGENT_LOG_FILENAME = "agent_log"
DIRECTOR_LOG_FILENAME = "director_log"
CERT_PEM_FILENAME = "cert.pem"
KEY_PEM_FILENAME = "key.pem"

ENSEMBLE_WEB_FILE = "ensemble_web.py"

ECHO_COMMAND = "echo"
STAT_COMMAND = "stat --printf='%s' .logs/agent_log"
PROCESS_COMMAND = "ps -aux"
SHUTDOWN_COMMAND = "shutdown"
REBOOT_COMMAND = "reboot"
KILL_COMMAND = "kill -9"
MAKE_DIR_COMMAND = "mkdir"
OPENSSL_GENERATE_CERT_AND_KEY_COMMAND = """openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365 -subj "/C=UA/ST=Kharkov/L=Kharkov/O=NSA/OU=IT Department/CN=ensemble_director.com" """


CONFIG_FILE_HOST_IP = "HostIp"
CONFIG_FILE_AGENT_REG_PORT = "AgentRegistrationPort"
CONFIG_FILE_AGENT_COM_PORT = "AgentCommunicationPort"

NA = "n/a"
UTF8 = "utf-8"

CLEAR_COMPLETE_JOBS_COMMAND = "Clear"
KILL_ALL_JOBS_COMMAND = "Kill"
STOP_ALL_JOBS = "StopJobs"
RESTART_AGENT = "Restart"
KILL_AGENT = "Kill"

ID_ARG = "id"
SET_WORKSPACE_ARG = "setWorkspace"
CMD_ARG = "cmd"
AGENT_ID_ARG = "agentId"
DUPLICATE_ARG = "duplicate"
DISMISS_ARG = "dismiss"
TARGET_ARG = "target"
TARGETS_ARG = "targets"
SINGLE_COMMAND_ARG = "isSingleCmd"
IS_LOADBALANCED_ARG = "isLoadBalanced"
RUN_TIME_ARG = "runTime"
RUN_DATE_TIME_ARG = "runDateTime"
RUN_TYPE_ARG = "runType"
SCHEDULED_JOB_ARG = "scheduledJob"
JOB_DATA_ARG = "jobData"

USER_TOKEN = "user"
CURRENT_WORKSPACE_ID_TOKEN = "currentWorkspaceId"
LOCATION_HEADER = "location"

GET = "GET"
POST = "POST"
PUT = "PUT"
DELETE = "DELETE"
CONTENT_TYPE_HEADER = "ContentType"
APPLICATION_JSON = "application/json"
SUCCESS = 200
UNAUTHORIZED = 401
SERVER_ERROR = 500

ROOT_WEB_DIR = "/"
API_PATH = "/api"
API_LOGSTREAM = API_PATH + "/logstream"
API_JOBS = API_PATH + "/jobs"
API_SCHEDULED_JOBS = API_PATH + "/scheduled_jobs"
API_SCHEDULED_JOB_RESULT_INFO = API_PATH + "/scheduledjobresultinfo"
API_SCHEDULED_JOB_RESULTS = API_PATH + "/scheduledjobresults"
API_AGENTS = API_PATH + "/agents"
API_AGENT_HEALTH = API_PATH + "/agent_health"
API_ADD_TARGET = API_PATH + "/addTarget"
API_REMOVE_TARGET = API_PATH + "/removeTarget"
API_UPDATE_PASSWORD = API_PATH + "/updatePassword"
API_GET_SERVER_TIME = API_PATH + "/getTime"
API_DELETE_SCHEDULED_JOB = API_PATH + "/deletescheduledjob"
API_GET_COMMAND_TEMPLATES = API_PATH + "/getCommandTemplates"
API_ADD_COMMAND_TEMPLATES = API_PATH + "/addCommandTemplates"
API_DELETE_COMMAND_TEMPLATES = API_PATH + "/deleteCommandTemplates"

DASHBOARD_PATH = "/dashboard"
WORKSPACE_PATH = "/workspace"
AGENT_HEALTH_PATH = "/agenthealth"
AGENTS_PATH = "/agents"
JOB_RESULTS_PATH = "/jobresults"
JOBS_PATH = "/jobs"
SCHEDULED_JOB_RESULTS_PATH = "/scheduledjobresults"
SCHEDULED_JOBS_PATH = "/scheduledjobs"
AGENT_COMMANDS_PATH = "/agentCommands"
NEW_JOB_PATH = "/newjob"
STREAM_EVENTS_PATH = "/streamevents"
MESSAGES_PATH = "/messages"
SETTINGS_PATH = "/settings"
LOGOUT_PATH = "/logout"

LOGIN_PAGE = "login.html"
CREATE_ADMIN_PAGE = "createadminuser.html"
DASHBOARD_PAGE = "dashboard.html"
AGENT_HEALTH_PAGE = "agenthealth.html"
AGENTS_PAGE = "agents.html"
JOBS_PAGE = "jobs.html"
SCHEDULED_JOBS_PAGE = "scheduledjobs.html"
SCHEDULED_JOB_RESULTS_PAGE = "scheduledjobresults.html"
JOB_RESULTS_PAGE = "jobresults.html"
NEW_JOB_PAGE = "newjob.html"
STREAM_EVENTS_PAGE = "events.html"
SETTINGS_PAGE = "settings.html"